export default props => {
	const {
		border,
		borderColor,
		borderWidth,
		borderBottom,
		borderBottomColor,
		borderBottomStyle,
		borderBottomWidth,
		borderLeft,
		borderLeftColor,
		borderLeftStyle,
		borderLeftWidth,
		borderRight,
		borderRightColor,
		borderRightStyle,
		borderRightWidth,
		borderTop,
		borderTopColor,
		borderTopStyle,
		borderTopWidth,
	} = props;

	return {
		border,
		borderColor,
		borderWidth,
		borderBottom,
		borderBottomColor,
		borderBottomStyle,
		borderBottomWidth,
		borderLeft,
		borderLeftColor,
		borderLeftStyle,
		borderLeftWidth,
		borderRight,
		borderRightColor,
		borderRightStyle,
		borderRightWidth,
		borderTop,
		borderTopColor,
		borderTopStyle,
		borderTopWidth,
	};
};